import { ReactElement } from "react";
import {
  AddUser,
  Ava,
  Back,
  Calendar,
  Change,
  Close,
  Date,
  Delete,
  Down,
  Down2,
  Download,
  Edit,
  Exit,
  Eye,
  More,
  Next,
  Pencil,
  Plus,
  Prev,
  Print,
  RasxodFioIcon,
  Search,
  Settings,
  Up,
  Us,
} from "./icons";

import {
  Andijon,
  Buxoro,
  Fargona,
  Jizzax,
  Namangan,
  Navoiy,
  Qashqadaryo,
  Qoraqalpoq,
  Samarqand,
  Sirdaryo,
  Surxondaryo,
  Tashkent,
  TashkentR,
  Xorazm,
} from "./map/regions";
import UzbMap, { datas } from "./map/uzb";
import {
  Batalon,
  BottomArrow,
  FIO,
  Hisobot,
  Home,
  Kattalashtir,
  Organizatsiya,
  Shartnoma,
  Spravochnik,
  TopArrow,
  Users,
} from "./navbar/icons";

// const Icons: {
//   [key: string]: { icon: ReactElement; lightIcon?: ReactElement };
// } = {
//   back: { icon: <Back /> },
//   plus: { icon: <Plus /> },
//   eye: { icon: <Eye /> },
//   pencil: { icon: <Pencil /> },
//   delete: { icon: <Delete /> },
//   prev: { icon: <Prev /> },
//   next: { icon: <Next /> },
//   add_user: { icon: <AddUser /> },
//   ava: { icon: <Ava /> },
//   calendar: { icon: <Calendar /> },
//   change: { icon: <Change /> },
//   exit: { icon: <Exit /> },
//   close: { icon: <Close /> },
//   date: { icon: <Date /> },
//   down: { icon: <Down /> },
//   down2: { icon: <Down2 /> },
//   edit: { icon: <Edit /> },
//   search: { icon: <Search /> },
//   up: { icon: <Up /> },
//   us: { icon: <Us /> },
//   home: { icon: <Home /> },
//   shartnoma: { icon: <Shartnoma /> },
//   batalon: { icon: <Batalon /> },
//   hisobot: { icon: <Hisobot /> },
//   organizatsiya: { icon: <Organizatsiya /> },
//   spravochnik: { icon: <Spravochnik /> },
//   fio: { icon: <FIO /> },
//   kattalashtir: { icon: <Kattalashtir /> },
//   bottom_arrow: { icon: <BottomArrow /> },
//   download: { icon: <Download /> },
//   print: { icon: <Print /> },
//   more: { icon: <More /> },
//   rasxod_fio: { icon: <RasxodFioIcon /> },
//   top_arrow: { icon: <TopArrow /> },
//   uzb_map: { icon: <UzbMap datas={datas} /> },
//   users: { icon: <Users /> },
//   tashkent_v: { icon: <TashkentR /> },
//   tashkent: { icon: <Tashkent /> },
//   andijon: { icon: <Andijon /> },
//   buxoro: { icon: <Buxoro /> },
//   jizzax: { icon: <Jizzax /> },
//   namangan: { icon: <Namangan /> },
//   navoiy: { icon: <Navoiy /> },
//   qashqadaryo: { icon: <Qashqadaryo /> },
//   xorazm: { icon: <Xorazm /> },
//   qoraqalpoq: { icon: <Qoraqalpoq /> },
//   sirdaryo: { icon: <Sirdaryo /> },
//   surxondaryo: { icon: <Surxondaryo /> },
//   samarqand: { icon: <Samarqand /> },
//   fargona: { icon: <Fargona /> },
// };
const Icons: {
  [key: string]: (props: any) => ReactElement;
} = {
  back: (props) => <Back {...props} />,
  plus: (props) => <Plus {...props} />,
  eye: (props) => <Eye {...props} />,
  pencil: (props) => <Pencil {...props} />,
  delete: (props) => <Delete {...props} />,
  prev: (props) => <Prev {...props} />,
  next: (props) => <Next {...props} />,
  add_user: (props) => <AddUser {...props} />,
  ava: (props) => <Ava {...props} />,
  calendar: (props) => <Calendar {...props} />,
  change: (props) => <Change {...props} />,
  exit: (props) => <Exit {...props} />,
  close: (props) => <Close {...props} />,
  date: (props) => <Date {...props} />,
  down: (props) => <Down {...props} />,
  down2: (props) => <Down2 {...props} />,
  edit: (props) => <Edit {...props} />,
  search: (props) => <Search {...props} />,
  up: (props) => <Up {...props} />,
  us: (props) => <Us {...props} />,
  home: (props) => <Home {...props} />,
  shartnoma: (props) => <Shartnoma {...props} />,
  batalon: (props) => <Batalon {...props} />,
  hisobot: (props) => <Hisobot {...props} />,
  organizatsiya: (props) => <Organizatsiya {...props} />,
  spravochnik: (props) => <Spravochnik {...props} />,
  fio: (props) => <FIO {...props} />,
  kattalashtir: (props) => <Kattalashtir {...props} />,
  bottom_arrow: (props) => <BottomArrow {...props} />,
  download: (props) => <Download {...props} />,
  print: (props) => <Print {...props} />,
  more: (props) => <More {...props} />,
  rasxod_fio: (props) => <RasxodFioIcon {...props} />,
  top_arrow: (props) => <TopArrow {...props} />,
  uzb_map: (props) => <UzbMap datas={datas} {...props} />,
  users: (props) => <Users {...props} />,
  tashkent_v: (props) => <TashkentR {...props} />,
  tashkent: (props) => <Tashkent {...props} />,
  andijon: (props) => <Andijon {...props} />,
  buxoro: (props) => <Buxoro {...props} />,
  jizzax: (props) => <Jizzax {...props} />,
  namangan: (props) => <Namangan {...props} />,
  navoiy: (props) => <Navoiy {...props} />,
  qashqadaryo: (props) => <Qashqadaryo {...props} />,
  xorazm: (props) => <Xorazm {...props} />,
  qoraqalpoq: (props) => <Qoraqalpoq {...props} />,
  sirdaryo: (props) => <Sirdaryo {...props} />,
  surxondaryo: (props) => <Surxondaryo {...props} />,
  samarqand: (props) => <Samarqand {...props} />,
  fargona: (props) => <Fargona {...props} />,
  settings: (props) => <Settings {...props} />,
};

export const iconNames = [
  "users",
  "settings",
  "fargona",
  "samarqand",
  "sirdaryo",
  "surxondaryo",
  "qoraqalpoq",
  "xorazm",
  "qashqadaryo",
  "namangan",
  "navoiy",
  "jizzax",
  "buxoro",
  "andijon",
  "tashkent_v",
  "tashkent",
  "uzb_map",
  "more",
  "print",
  "download",
  "kattalashtir",
  "fio",
  "spravochnik",
  "organizatsiya",
  "hisobot",
  "batalon",
  "shartnoma",
  "home",
  "us",
  "up",
  "search",
  "edit",
  "down",
  "down2",
  "date",
  "close",
  "exit",
  "change",
  "calendar",
  "ava",
  "back",
  "plus",
  "eye",
  "pencil",
  "delete",
  "prev",
  "next",
  "add_user",
  "bottom_arrow",
  "top_arrow",
  "rasxod_fio",
] as const;

export type IconName = (typeof iconNames)[number];

type Props = {
  name: IconName;
  active?: boolean; // Misol uchun yangi prop
  color?: string; // Ixtiyoriy qo'shimcha prop
};

const Icon = ({ name, ...props }: Props): ReactElement => {
  const IconComponent = Icons[name];
  if (!IconComponent) {
    return <div>Icon not found</div>;
  }
  // const result = Icons?.[name]["icon"] || undefined;
  return (
    <div className="w-[inherit] h-[inherit] cursor-pointer flex items-center">
      <IconComponent {...props} />
    </div>
  );
};

export default Icon;
